# Generated by Django 4.2 on 2023-12-31 12:15

import administration.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='block_code',
            field=administration.models.FixedCharField(max_length=16, unique=True),
        ),
    ]
