# Generated by Django 4.2 on 2023-12-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=6)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
