# Generated by Django 4.2 on 2023-12-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scanner',
            table='scanners',
        ),
    ]
