# Generated by Django 4.2 on 2023-12-28 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import focaccine.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scan', '0001_initial'),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', focaccine.models.FixedCharField(max_length=17, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', focaccine.models.FixedCharField(choices=[('OPEN', 'Unused'), ('PEND', 'Pending'), ('HOLD', 'On-hold'), ('USED', 'Used')], default='OPEN', max_length=4)),
                ('date_used', models.DateTimeField(default=None, null=True)),
                ('type', models.CharField(choices=[('FOCACCINA', 'Focaccina'), ('PRANZO', 'Pranzo'), ('CENA', 'Cena'), ('ALTRO', 'Altro')], default='FOCACCINA', max_length=16)),
                ('block_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.transaction', to_field='block_code')),
                ('scanner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scan.scanner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
