# Generated by Django 4.2 on 2023-12-31 12:15

from django.db import migrations
import focaccine.models


class Migration(migrations.Migration):

    dependencies = [
        ('focaccine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_code',
            field=focaccine.models.FixedCharField(max_length=16, unique=True),
        ),
    ]
